{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "selectel-billing-exporter.fullname" . }}-metrics
  {{- if .Values.metrics.serviceMonitor.namespace }
  namespace: {{ .Values.metrics.serviceMonitor.namese 
  {{- end 
  labels: {{- include "selectel-billing-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- range $key, $value := .Values.metrics.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      path: "/metrics"
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Names
