apiVersion: v1
kind: Service
metadata:
  name: {{ include "selectel-billing-exporter.fullname" . }}
  labels:
    {{- include "selectel-billing-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    {{- include "selectel-billing-exporter.selectorLabels" . | nindent 4 }}
